---
phases: 
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push zawye21/simple:latest"
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t zawye21/simple ."
      - "docker tag zawye21/simple zawye21/simple:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=zawye21 --password=n0thing."
version: 0.1

